sonar.projectKey=smart-school-management-system
sonar.projectName=Smart School Management System
sonar.sources=frontend/src,backend/src/main/java
sonar.tests=backend/src/test
sonar.exclusions=frontend/node_modules/**,frontend/dist/**,backend/target/**
sonar.sourceEncoding=UTF-8
