spring.application.name=smart-school-backend
server.port=8080

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/smart_school?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
#gérer une base existante
spring.flyway.baseline-on-migrate=true

app.jwt.secret=${JWT_SECRET:SmartSchoolSecureJwtKey2026DevelopmentX9K7mP4qL2vN8sR5}
#24h
app.jwt.expiration=86400000
app.frontend.url=${FRONTEND_URL:http://localhost:5173}
